plugins {
    id 'java'
    id 'com.github.johnrengelman.shadow' version '8.1.1'
    id 'org.jetbrains.kotlin.jvm'
}

group = 'com.pumpkin.msg'
version = '1.3'

base {
    archivesName = 'PumpkinMsg'
}

repositories {
    mavenCentral()
    maven {
        name = 'papermc'
        url = 'https://repo.papermc.io/repository/maven-public/'
    }
    maven { url "https://repo.lucko.me/" }
    maven { url "https://repo.extendedclip.com/releases/" }
}

dependencies {
    compileOnly 'io.papermc.paper:paper-api:1.19.4-R0.1-SNAPSHOT'
    compileOnly 'com.velocitypowered:velocity-api:3.3.0-SNAPSHOT'
    annotationProcessor 'com.velocitypowered:velocity-api:3.3.0-SNAPSHOT'
    compileOnly 'me.clip:placeholderapi:2.12.2'
    compileOnly 'net.kyori:adventure-text-minimessage:4.17.0'
    compileOnly 'net.kyori:adventure-api:4.17.0'

    compileOnly "net.luckperms:api:5.5"

    implementation 'com.moandjiezana.toml:toml4j:0.7.2'
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8"
}

def targetJavaVersion = 17
java {
    def commonJavaVersion = JavaVersion.toVersion(targetJavaVersion)
    sourceCompatibility = commonJavaVersion
    targetCompatibility = commonJavaVersion
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    if (JavaVersion.current().isJava10Compatible()) {
        options.release.set(targetJavaVersion)
    }
}

shadowJar {
    archiveFileName.set("PumpkinMsg-${project.version}.jar")
    relocate 'com.moandjiezana.toml', 'com.pumpkin.msg.libs.toml'
}

build.dependsOn shadowJar

kotlin {
    jvmToolchain(17)
}
